export const toolTags: Record<string, string[]> = {
  "word-counter": ["Writing", "SEO"],
  "case-converter": ["Writing", "Formatting"],
  "remove-line-breaks": ["Cleaning", "Formatting"],
  "remove-duplicate-lines": ["Cleaning", "Lists"],
  "text-sorter": ["Sorting", "Lists"],
  "whitespace-cleaner": ["Cleaning", "Dev"],
  "reverse-text": ["Fun", "Formatting"],
  "character-counter": ["Writing", "SEO"],
  "url-encoder-decoder": ["Dev", "Formatting"],
  "text-case-swapper": ["Writing", "Formatting"],
  "slug-generator": ["Dev", "SEO", "Formatting"],
  "json-formatter": ["Dev", "Formatting", "Debugging"],
  "html-stripper": ["Cleaning", "Dev", "Formatting"],
  "text-deduplicator": ["Writing", "Cleaning", "Lists"],
  "list-to-csv": ["Lists", "Formatting", "Dev"],
  "csv-to-table": ["Dev", "Formatting", "Lists"],
  "text-to-html": ["Dev", "Formatting", "HTML"],
  "regex-tools": ["Dev", "Text Matching", "Advanced"],
  "text-trimmer": ["Cleaning", "Formatting", "Lists"],
  "number-extractor": ["Data", "Dev", "Cleaning"],
  "word-frequency-counter": ["SEO", "Writing", "Analysis"],
  "text-encoder-decoder": ["Dev", "Security", "Encoding"],
  "text-splitter": ["Formatting", "Dev", "Analysis"],
  "string-length-checker": ["Writing", "SEO", "Limits"],
  "symbol-remover": ["Cleaning", "Dev", "Sanitizing"],
  "text-to-markdown": ["Writing", "Dev", "Formatting"],
}